name: GitHub Actions Demo

on:
  push:
    branches: main
    paths-ignore: .github/**
  pull_request:
    branches: main
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Triggering Event: ${{ github.event_name}}"
          echo "Branch: ${{ github.ref }}"

      - uses: actions/checkout@v3.3.0

      - name: List files in the repository
        run: |
          echo "Files:"
          tree
  Test:
    runs-on: ubuntu-latest
    needs: Build
    if: github.event_name == 'workflow_dispatch'
    environment: Test
    steps:
      - run: echo 'Testing...'
  Load-Test:
    runs-on: ubuntu-latest
    needs: Build
    if: github.event_name == 'workflow_dispatch'
    steps:
      - run: echo 'Testing...'
      - run: sleep 15
  Production:
    runs-on: ubuntu-latest
    needs: [Test, Load-Test]
    if: github.event.inputs.environment == 'Production'
    environment:
      name: Production
      url: https://writeabout.net
    steps:
      - run: echo 'Step 1 deploying...'
      - run: sleep 10
      - run: echo 'Step 2 deploying...'
      - run: sleep 10
      - run: echo 'Step 3 deploying...'
      - run: sleep 10
      - run: echo 'Step 4 deploying...'
      - run: sleep 10
      - run: echo 'Step 5 deploying...'
      - run: sleep 10
